/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ScoreColumn: typeof import('./src/components/ScoreColumn.vue')['default']
    ScoreColumnBase: typeof import('./src/components/ScoreColumnBase.vue')['default']
    ScoreColumnCircle: typeof import('./src/components/ScoreColumnCircle.vue')['default']
    ScoreInfo: typeof import('./src/components/ScoreInfo.vue')['default']
  }
}
